# =============================================================================
# models.py — Pydantic schemas for API request and response bodies
# =============================================================================
# WHY THIS FILE EXISTS:
# FastAPI uses Pydantic models to:
#   1. Validate incoming JSON — reject malformed requests automatically
#   2. Serialize outgoing JSON — ensure consistent response shapes
#   3. Generate OpenAPI docs — the /docs page reads these schemas to show
#      developers exactly what fields are expected and what they'll get back
#
# Keeping models in their own file (rather than inline in main.py) means:
#   - main.py stays focused on routing logic
#   - models can be imported by tests, services, etc. without circular deps
#   - when we add Redis memory later, we add new models here without
#     cluttering the endpoint definitions
# =============================================================================

from pydantic import BaseModel, Field


# =============================================================================
# ChatRequest — What the client sends to POST /chat
# =============================================================================
class ChatRequest(BaseModel):
    """
    The payload a client sends when they want to chat with Claude.

    Example JSON body:
    {
        "message": "Hi, my name is Matthew!",
        "session_id": "user-123-session-abc"
    }
    """

    # The user's message text. This is the only truly required field.
    # `min_length=1` prevents empty strings — there's no point sending
    # a blank message to Claude (it would waste an API call).
    # The Field() call also provides description text that shows up in
    # the auto-generated /docs page.
    message: str = Field(
        ...,                            # ... means "required, no default"
        min_length=1,                   # reject empty strings
        description="The user's message to send to Claude.",
        examples=["Hi, my name is Matthew!"],  # shown in /docs UI
    )

    # A unique identifier for the conversation session.
    # WHY THIS MATTERS FOR LATER:
    # Right now (Task 1), we don't persist anything — each request is
    # independent. But when we add Redis in Task 2, this session_id
    # becomes the key under which we store chat history. By including
    # it now, the API contract won't change when we add memory.
    #
    # Default is "default" so the API works out-of-the-box without
    # requiring clients to generate session IDs for simple testing.
    session_id: str = Field(
        default="default",
        description=(
            "Unique session identifier. Used to group messages into "
            "conversations. Will be used as the Redis key for chat "
            "history in a future phase."
        ),
        examples=["user-123-session-abc"],
    )


# =============================================================================
# ChatResponse — What the server sends back from POST /chat
# =============================================================================
class ChatResponse(BaseModel):
    """
    The payload returned after Claude processes a message.

    Example JSON response:
    {
        "response": "Hi Matthew! Nice to meet you. How can I help?",
        "session_id": "user-123-session-abc",
        "model": "claude-haiku-4-5",
        "usage": {
            "input_tokens": 42,
            "output_tokens": 18
        }
    }
    """

    # Claude's text response to the user's message.
    response: str = Field(
        ...,
        description="The text response generated by Claude.",
    )

    # Echo back the session_id so the client can confirm which session
    # this response belongs to. Useful when a client manages multiple
    # concurrent conversations.
    session_id: str = Field(
        ...,
        description="The session ID this response belongs to.",
    )

    # Which Claude model actually generated the response.
    # We include this for transparency — during demos, it's helpful to
    # show exactly which model is being used (e.g., haiku vs. sonnet).
    model: str = Field(
        ...,
        description="The Claude model that generated this response.",
    )

    # Token usage statistics from the Anthropic API.
    # WHY INCLUDE THIS?
    #   - Demo value: shows the audience that LLM calls have measurable cost
    #   - Debugging: helps identify if prompts are unexpectedly large
    #   - Future: when we add Redis memory/context, we can show how
    #     injecting history increases input token count
    usage: dict = Field(
        ...,
        description=(
            "Token usage statistics. Contains 'input_tokens' and "
            "'output_tokens' counts from the Anthropic API."
        ),
    )


# =============================================================================
# HealthResponse — What the server sends back from GET /health
# =============================================================================
class HealthResponse(BaseModel):
    """
    Simple health-check response. Confirms the server is running and
    reports which model is configured.

    Useful for:
      - Load balancers / uptime monitors
      - Quick "is it working?" checks during demos
      - Verifying the correct model is configured
    """

    # Always "ok" if the server is healthy enough to respond.
    status: str = Field(
        ...,
        description="Server health status.",
        examples=["ok"],
    )

    # Which model the server is configured to use.
    # Helpful during demos to confirm you're hitting the right model.
    model: str = Field(
        ...,
        description="The Claude model currently configured.",
    )
