"""Pydantic schemas for API request and response bodies.

FastAPI uses these models to validate incoming JSON, serialize
outgoing responses, and generate OpenAPI documentation.
"""

from typing import Literal

from pydantic import BaseModel, Field


class MemoryContext(BaseModel):
    """Metadata describing the memory state that informed a chat response.

    Each response carries its own snapshot because the counts change
    over time (e.g. ``messages_loaded`` grows with each exchange).

    Attributes:
        memory_mode: Which memory mode was active for the request.
        messages_loaded: Number of prior messages loaded from the
            session transcript.
        long_term_memories_retrieved: Number of durable long-term
            facts retrieved for this user identity.
    """

    memory_mode: Literal["none", "short-term", "long-term"] = Field(
        ...,
        description=(
            "The memory mode that was active when this response was generated."
        ),
    )

    messages_loaded: int = Field(
        default=0,
        description=(
            "Number of prior conversation messages loaded from the session "
            "transcript in Redis before sending the request to Claude."
        ),
    )

    long_term_memories_retrieved: int = Field(
        default=0,
        description=(
            "Number of long-term memories retrieved from Redis for this "
            "user identity. Only applies to long-term memory mode."
        ),
    )


class ChatRequest(BaseModel):
    """Payload sent by the client to ``POST /chat``.

    Attributes:
        message: The user's message text.
        session_id: Unique identifier grouping messages into a
            conversation and selecting the correct working-memory
            transcript.
        memory_mode: Controls how the backend handles memory for
            this request.
        user_id: Stable user identity linking multiple long-term
            conversations together.
    """

    message: str = Field(
        ...,
        min_length=1,
        description="The user's message to send to Claude.",
        examples=["Hi, my name is Matthew!"],
    )

    session_id: str = Field(
        default="default",
        description=(
            "Unique session identifier. Used to group messages into "
            "conversations and load the correct working-memory transcript."
        ),
        examples=["user-123-session-abc"],
    )

    memory_mode: Literal["none", "short-term", "long-term"] = Field(
        default="none",
        description=(
            "How the backend should handle memory for this request. "
            "'none' keeps the request stateless, 'short-term' uses session "
            "history, and 'long-term' combines session history with "
            "user-level fact memory across chats."
        ),
        examples=["short-term"],
    )

    user_id: str | None = Field(
        default=None,
        description=(
            "Stable user identifier used to link multiple long-term "
            "conversations together. Primarily used when memory_mode is "
            "'long-term'."
        ),
        examples=["default-user"],
    )


class ChatResponse(BaseModel):
    """Payload returned after Claude processes a message.

    Attributes:
        response: Claude's text reply.
        session_id: The session this response belongs to.
        model: The Claude model that generated the response.
        usage: Token usage statistics with ``input_tokens`` and
            ``output_tokens`` counts.
        user_id: Resolved stable user identity, when applicable.
        memory_context: Metadata about the memory state used to
            generate this response.
    """

    response: str = Field(
        ...,
        description="The text response generated by Claude.",
    )

    session_id: str = Field(
        ...,
        description="The session ID this response belongs to.",
    )

    model: str = Field(
        ...,
        description="The Claude model that generated this response.",
    )

    usage: dict = Field(
        ...,
        description=(
            "Token usage statistics. Contains 'input_tokens' and "
            "'output_tokens' counts from the Anthropic API."
        ),
    )

    user_id: str | None = Field(
        default=None,
        description=(
            "Resolved stable user identifier for the request, when applicable."
        ),
    )

    memory_context: MemoryContext | None = Field(
        default=None,
        description=(
            "Metadata about the memory state used to generate this response. "
            "Includes memory mode, messages loaded, and long-term facts retrieved."
        ),
    )


class ChatMessage(BaseModel):
    """A single chat message in API responses.

    Uses a consistent ``role`` + ``content`` shape, with an optional
    timestamp when available from stored memory records.

    Attributes:
        role: Whether the message came from the user or assistant.
        content: The message text.
        timestamp: ISO timestamp for when the message was created,
            if known.
    """

    role: Literal["user", "assistant"] = Field(
        ...,
        description="Whether the message came from the user or assistant.",
    )
    content: str = Field(
        ...,
        description="The message text.",
    )
    timestamp: str | None = Field(
        default=None,
        description="ISO timestamp for when the message was created, if known.",
    )


class LongTermChatSummary(BaseModel):
    """Lightweight metadata about an archived long-term conversation.

    Provides enough information for a list view without loading the
    full transcript.

    Attributes:
        session_id: Unique identifier for the archived chat session.
        label: Human-friendly label for the chat.
        message_count: Total number of stored messages.
        last_updated: ISO timestamp of the most recent activity.
        preview: Short preview of the most recent content.
    """

    session_id: str = Field(
        ...,
        description="Unique identifier for the archived chat session.",
    )
    label: str = Field(
        ...,
        description="Human-friendly label for the chat.",
    )
    message_count: int = Field(
        ...,
        description="Total number of stored messages in the chat.",
    )
    last_updated: str | None = Field(
        default=None,
        description="ISO timestamp of the most recent activity in the chat.",
    )
    preview: str | None = Field(
        default=None,
        description="Short preview of the most recent user-facing content.",
    )


class LongTermChatsResponse(BaseModel):
    """Response for the long-term chat archive listing endpoint.

    Attributes:
        user_id: Stable user identity used for the archive lookup.
        chats: Archived long-term chat summaries for the user.
    """

    user_id: str = Field(
        ...,
        description="Stable user identifier used for the archive lookup.",
    )
    chats: list[LongTermChatSummary] = Field(
        ...,
        description="Archived long-term chats for the user.",
    )


class LongTermChatResponse(BaseModel):
    """Full transcript for one archived long-term conversation.

    Attributes:
        user_id: Stable user identity that owns the chat.
        session_id: The archived chat session that was loaded.
        label: Human-friendly label for the archived chat.
        messages: Ordered transcript of the archived chat.
    """

    user_id: str = Field(
        ...,
        description="Stable user identifier that owns the chat.",
    )
    session_id: str = Field(
        ...,
        description="The archived chat session that was loaded.",
    )
    label: str = Field(
        ...,
        description="Human-friendly label for the archived chat.",
    )
    messages: list[ChatMessage] = Field(
        ...,
        description="Transcript of the archived chat.",
    )


class LongTermFact(BaseModel):
    """A durable fact persisted across long-term chat sessions.

    Attributes:
        id: Server-assigned unique identifier for the memory record.
        text: Human-readable fact text stored in long-term memory.
        topics: Topic labels attached to the fact for organization.
        entities: Key entities or values associated with the fact.
        memory_type: Classification of the memory — ``semantic`` for
            general facts, ``episodic`` for time-grounded events.
        event_date: ISO timestamp for the event date when this is an
            episodic memory.
        source_session_id: Chat session where the fact was first
            observed, if known.
    """

    id: str | None = Field(
        default=None,
        description="Server-assigned unique identifier for the memory record.",
    )
    text: str = Field(
        ...,
        description="Human-readable fact text stored in long-term memory.",
    )
    topics: list[str] = Field(
        default_factory=list,
        description="Topic labels attached to the fact for organization.",
    )
    entities: list[str] = Field(
        default_factory=list,
        description="Key entities or values associated with the fact.",
    )
    memory_type: Literal["semantic", "episodic", "message"] | None = Field(
        default=None,
        description=(
            "What kind of memory this is. 'semantic' stores general facts, "
            "while 'episodic' stores time-grounded events."
        ),
    )
    event_date: str | None = Field(
        default=None,
        description=(
            "ISO timestamp for the event date when this is an episodic memory."
        ),
    )
    source_session_id: str | None = Field(
        default=None,
        description="Chat session where the fact was first observed, if known.",
    )


class LongTermFactsResponse(BaseModel):
    """Current long-term fact set for one user identity.

    Attributes:
        user_id: Stable user identity whose facts were loaded.
        facts: Currently remembered long-term facts for the user.
    """

    user_id: str = Field(
        ...,
        description="Stable user identifier whose facts were loaded.",
    )
    facts: list[LongTermFact] = Field(
        default_factory=list,
        description="Currently remembered long-term facts for that user.",
    )


class DeleteFactsRequest(BaseModel):
    """Payload for deleting one or more long-term memories by ID.

    Attributes:
        memory_ids: Server-assigned identifiers of the memories to
            remove.
    """

    memory_ids: list[str] = Field(
        ...,
        min_length=1,
        description="List of memory IDs to delete.",
    )


class DeleteFactsResponse(BaseModel):
    """Acknowledgement returned after deleting long-term memories.

    Attributes:
        deleted_count: Number of memories that were actually removed.
        memory_ids: The IDs that were requested for deletion.
    """

    deleted_count: int = Field(
        ...,
        description="Number of memories that were removed.",
    )
    memory_ids: list[str] = Field(
        ...,
        description="The memory IDs that were requested for deletion.",
    )


class UpdateFactRequest(BaseModel):
    """Payload for editing one long-term memory.

    All fields are optional — only the supplied fields are updated on
    the server.

    Attributes:
        text: Updated human-readable fact text.
        topics: Updated topic labels.
        entities: Updated entity list.
        memory_type: Updated memory classification.
        event_date: Updated event date for episodic memories.
    """

    text: str | None = Field(
        default=None,
        description="Updated text content for the memory.",
    )
    topics: list[str] | None = Field(
        default=None,
        description="Updated topic labels for the memory.",
    )
    entities: list[str] | None = Field(
        default=None,
        description="Updated entity list for the memory.",
    )
    memory_type: Literal["semantic", "episodic", "message"] | None = Field(
        default=None,
        description="Updated memory type classification.",
    )
    event_date: str | None = Field(
        default=None,
        description="Updated event date (ISO format) for episodic memories.",
    )


class UpdateFactResponse(BaseModel):
    """Response after successfully editing a long-term memory.

    Attributes:
        fact: The updated memory record.
    """

    fact: LongTermFact = Field(
        ...,
        description="The updated memory record.",
    )


class ForgetFactsRequest(BaseModel):
    """Policy-driven request to expire stale long-term memories.

    At least one policy field must be set. The server scans matching
    memories and removes those that exceed the specified thresholds.

    Attributes:
        max_age_days: Remove memories older than this many days.
        max_inactive_days: Remove memories not accessed within this
            many days.
        dry_run: When ``True``, report what would be deleted without
            actually removing anything.
    """

    max_age_days: int | None = Field(
        default=None,
        ge=1,
        description="Remove memories older than this many days.",
    )
    max_inactive_days: int | None = Field(
        default=None,
        ge=1,
        description=(
            "Remove memories not accessed within this many days."
        ),
    )
    dry_run: bool = Field(
        default=False,
        description=(
            "When true, report what would be deleted without actually "
            "removing anything."
        ),
    )


class ForgetFactsResponse(BaseModel):
    """Summary of a policy-driven forgetting pass.

    Attributes:
        scanned: Total number of memories evaluated.
        deleted: Number of memories actually removed (zero when
            ``dry_run`` was ``True``).
        deleted_ids: Server-assigned IDs of the removed memories.
        dry_run: Whether this was a dry-run preview.
    """

    scanned: int = Field(
        ...,
        description="Total number of memories evaluated by the policy.",
    )
    deleted: int = Field(
        ...,
        description="Number of memories removed.",
    )
    deleted_ids: list[str] = Field(
        default_factory=list,
        description="Server-assigned IDs of the removed memories.",
    )
    dry_run: bool = Field(
        ...,
        description="Whether this was a dry-run preview.",
    )


class HealthResponse(BaseModel):
    """Health-check response confirming server status.

    Attributes:
        status: Server health status (``"ok"`` when healthy).
        model: The Claude model currently configured.
    """

    status: str = Field(
        ...,
        description="Server health status.",
        examples=["ok"],
    )
    model: str = Field(
        ...,
        description="The Claude model currently configured.",
    )
